### ISSUE TITLE
Crashing on "Open Receive to Bound Send Port"

### ISSUE THREAD

**Issue by ronald-jaepel** [getnamo/UDP-Unreal#22]
Hey, 

thank you for creating this very helpful plugin. I've stumbled upon a problem that I can't seem to work out on my own, so I wanted to ask for help. 

I want to interact with an existing UDP server that answers to the same port from which the client sent a request. So I need the receive IP and port to be identical to the send IP and port. However enabling the option "Should Open Receive to Bound Send Port" or manually setting them to be identical causes UE to crash with this error message:
`Assertion failed: Socket != nullptr [File:C:\Program Files\Epic Games\UE_4.26\Engine\Source\Runtime\Networking\Public\Common/UdpSocketReceiver.h] [Line: 53]`

Stepping through the socket opening process in the debugger shows that it fails when trying to bind the receiver socket in Line 301 of UdpSocketBuilder.h (UE_4.26\Engine\Source\Runtime\Networking\Public\Common\UdpSocketBuilder.h) without any further error message.

When trying to circumvent the problem by setting the receiver IP to 0.0.0.0 no packages are received anymore from the target IP address.

Specs: UE 4.26.2 on Windows 10 x64

Is this expected behavior or a bug?

**Comment by getnamo** [comment]
Opening to bound send port is not what you're looking for if you want a specific port. Turn that option off and specify each port manually

**Comment by ronald-jaepel** [comment]
hello getnamo, thank you for the quick reply! Much appreciated.

However I still can't figure it out. Are these two behaviors expected?:
1. During further tests I found that UE crashes as soon as I set Receiver Socket IP as any other IP than 0.0.0.0 or 127.0.0.1. Is that a bug on my system or expected?
2. with this setup: 
![image](https://user-images.githubusercontent.com/18073230/127544972-4065a66c-5bd0-491c-8a58-40d1f7851b69.png)
I can send but not receive any packets. 
To compare: When setting both IP adresses to 127.0.0.1 I can send and receive packages to another application on the same device
![image](https://user-images.githubusercontent.com/18073230/127544723-9a905b24-2c7d-4292-8b40-6f987314168c.png)
 This next config works as expected, in that I can send and receive packages
![image](https://user-images.githubusercontent.com/18073230/127545239-c663f66b-0956-4895-8f82-6797ec07c453.png)
but that doesn't help much because the server I'm trying to work with doesn't allow specifying a send target port, it always answers to the port from which it got a request.

**Comment by getnamo** [comment]
Receive up of 0.0.0.0 means all ips are valid, leave that as is. If you want to send and receive on port 26760 then specify that port for both send and receive.

**Comment by ronald-jaepel** [comment]
I'm sorry, I guess I haven't explained very well, because that's not what I want.

As an example: 

1. I open the send socket on device 1 (192.168.0.1) to send to device 2 at 192.168.0.2:**26760** 
2. Device 1 uses a random port to send from (e.g. **65432**), which afaik is returned by "Bound Port".
3. Device 2 gets a message from 192.168.0.1:**65432** 
4. Device 2 will send answer packages to 192.168.0.1:**65432** (and I can't change that because I don't have access to the servers source code)
5. Device 1 doesn't receive any input at **65432**, even if it's specified to be the Listen Port on the Receiving Socket with "Listen IP: 0.0.0.0" and I don't know why.

**Comment by ronald-jaepel** [comment]
I just found #7 and #18, which is exactly what I'm trying to do, and it works as long as server and client are on the same pc but stops working if they're on different pcs.

**Comment by vasilyevdm** [comment]
Faced same problem. Unreal Engine crashes when trying to bound Listen Port to the Bound Port while using 0.0.0.0. So actually there is no way to receive messages via NAT. Probably [Reuse](https://docs.unrealengine.com/4.26/en-US/API/Runtime/Sockets/FSocket/SetReuseAddr/) this option is not set on send socket?

**Comment by gstorer** [comment]
I think this line needs to be removed or commented out. It makes no sense to bind a ReceiveIP to the SendIP. It would only work in the case when everything is on the local machine like people say:
https://github.com/getnamo/udp-ue4/blob/d2109f715a377e65dc0e90daa3eb8bb1b6dd9b41/Source/UDPWrapper/Private/UDPComponent.cpp#L233

Alternatively we could grab the bound send IP address as well as the bound send port and use that. I think this function can get the right IP address:
https://docs.unrealengine.com/4.27/en-US/API/Runtime/Sockets/FSocket/GetAddress/

**Comment by getnamo** [comment]
Interesting, test your method and see if it works as expected, if so open a pull request and I'll merge it. Could probably set this up as a toggle option on whether to restrict to bound send IP or not.

**Comment by getnamo** [comment]
Merged in https://github.com/getnamo/UDP-Unreal/pull/24
