### ISSUE TITLE
How to specify a network adapter to send a UDP broadcast?

### ISSUE THREAD

**Issue by james-yoo** [getnamo/UDP-Unreal#27]
I have a network adapters that has four separate Ethernet ports (e.g. eth0, eth1, eth2, eth3) and all the ports have different IP address. Is it possible to specify port that I want to communicate on?

**Comment by getnamo** [comment]
I don't think this is supported in the plugin atm, you may want to identify the lower level Unreal call required on the ISocketSubsystem to select an adapter (see e.g. https://docs.unrealengine.com/4.27/en-US/API/Runtime/Sockets/ISocketSubsystem/GetLocalAdapterAddresses/) and when you've identified the calls required, make a pull request here with code changes and I'll merge the feature support.

**Comment by james-yoo** [comment]
@gstorer 
Thank you for your detailed response. I have resolved by setting **SendIP** and **ReceiveIP** manually.
