### ISSUE TITLE
Unreal crashes when opening the listen socket

### ISSUE THREAD

**Issue by abdullah-taqiaddin** [getnamo/UDP-Unreal#32]
hi @getnamo 
So i'm trying to open the listen socket but unreal crashes when it does 
it does send, i tested it on wireshark
I've turned off auto open for the receive 
![image](https://user-images.githubusercontent.com/72511000/218393249-51ff7b49-80d6-4c23-bbd0-fe0fae59e862.png)

**Comment by abdullah-taqiaddin** [comment]
even if i auto open receive it crashes

**Comment by getnamo** [comment]
Got a crash log?

**Comment by abdullah-taqiaddin** [comment]
Assertion failed: Socket != nullptr [File:C:\Program Files\Epic Games\UE_4.27\Engine\Source\Runtime\Networking\Public\Common/UdpSocketReceiver.h] [Line: 53]

UE4Editor_Core!AssertFailedImplV() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Private\Misc\AssertionMacros.cpp:104]
UE4Editor_Core!FDebug::CheckVerifyFailedImpl() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Private\Misc\AssertionMacros.cpp:461]
UE4Editor_UDPWrapper!FUDPNative::OpenReceiveSocket() [C:\Users\LENOVOG\Perforce\LowPollyTanks_Abdtaqi\Plugins\udp-ue4\Source\UDPWrapper\Private\UDPComponent.cpp:263]
UE4Editor_UDPWrapper!UUDPComponent::execOpenReceiveSocket() [C:\Users\LENOVOG\Perforce\LowPollyTanks_Abdtaqi\Plugins\udp-ue4\Intermediate\Build\Win64\UE4Editor\Inc\UDPWrapper\UDPComponent.gen.cpp:461]
UE4Editor_CoreUObject!UFunction::Invoke() [D:\Build\++UE4\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:5679]
UE4Editor_CoreUObject!UObject::CallFunction() [D:\Build\++UE4\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1023]
UE4Editor_CoreUObject!UObject::ProcessContextOpcode() [D:\Build\++UE4\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2896]
UE4Editor_CoreUObject!UObject::execLetBool() [D:\Build\++UE4\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2797]
UE4Editor_CoreUObject!ProcessLocalScriptFunction() [D:\Build\++UE4\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1093]
UE4Editor_CoreUObject!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [D:\Build\++UE4\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:924]
UE4Editor_CoreUObject!ProcessLocalFunction() [D:\Build\++UE4\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1154]
UE4Editor_CoreUObject!ProcessLocalScriptFunction() [D:\Build\++UE4\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1093]
UE4Editor_CoreUObject!UObject::ProcessInternal() [D:\Build\++UE4\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1181]
UE4Editor_CoreUObject!UFunction::Invoke() [D:\Build\++UE4\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:5679]
UE4Editor_CoreUObject!UObject::ProcessEvent() [D:\Build\++UE4\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2018]
UE4Editor_Engine!AActor::ProcessEvent() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Engine\Private\Actor.cpp:863]
UE4Editor_Engine!AActor::BeginPlay() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Engine\Private\Actor.cpp:3579]
UE4Editor_Engine!AActor::DispatchBeginPlay() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Engine\Private\Actor.cpp:3519]
UE4Editor_Engine!AWorldSettings::NotifyBeginPlay() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Engine\Private\WorldSettings.cpp:247]
UE4Editor_Engine!AGameStateBase::HandleBeginPlay() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Engine\Private\GameStateBase.cpp:205]
UE4Editor_Engine!UWorld::BeginPlay() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Engine\Private\World.cpp:4416]
UE4Editor_Engine!UGameInstance::StartPlayInEditorGameInstance() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Engine\Private\GameInstance.cpp:483]
UE4Editor_UnrealEd!UEditorEngine::CreateInnerProcessPIEGameInstance() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:2943]
UE4Editor_UnrealEd!UEditorEngine::OnLoginPIEComplete_Deferred() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:1503]
UE4Editor_UnrealEd!UEditorEngine::CreateNewPlayInEditorInstance() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:1750]
UE4Editor_UnrealEd!UEditorEngine::StartPlayInEditorSession() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:2713]
UE4Editor_UnrealEd!UEditorEngine::StartQueuedPlaySessionRequestImpl() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:1116]
UE4Editor_UnrealEd!UEditorEngine::StartQueuedPlaySessionRequest() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:1019]
UE4Editor_UnrealEd!UEditorEngine::Tick() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\EditorEngine.cpp:1629]
UE4Editor_UnrealEd!UUnrealEdEngine::Tick() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\UnrealEdEngine.cpp:426]
UE4Editor!FEngineLoop::Tick() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4921]
UE4Editor!GuardedMain() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:178]

**Comment by getnamo** [comment]
Appears to crash on `.BoundToEndpoint(Endpoint)` https://github.com/getnamo/UDP-Unreal/blob/master/Source/UDPWrapper/Private/UDPComponent.cpp#L263, put a breakpoint on that line or line 260 and see what the state of the values are at that point (launch in debugger from visual studio)

**Comment by AymenMenjli** [comment]
I have the same Crash after updating the new UE 5.1.1, in 5.1 the plugins work fine!!

**Comment by AymenMenjli** [comment]
> I have the same Crash after updating the new UE 5.1.1, in 5.1 the plugins work fine!!

Hey, I'm really sorry for the confusion it was my bad the crash was from the IP address. it works fine I just wanted to update this so there is no confusion

**Comment by abdullah-taqiaddin** [comment]
Hello @getnamo,Thanks for the assistance!
I've opted this for another tool (I've used the [PingQoS ](https://github.com/Yakim3396/PingQoS) if you are wondering) as it's more convenient for my use case, many thanks!
