### ISSUE TITLE
UE5.1 Editor crashes when stopping PIE while data is being received

### ISSUE THREAD

**Issue by Gliptal** [getnamo/UDP-Unreal#33]
Whenever PIE is stopped while a datastream is still sending UDP packets on a socket handled by UDPWrapper, the editor crashes with with the following trace:

> Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000008
>
> UnrealEditor_UDPWrapper!UE::Core::Private::Function::TFunctionRefBase<UE::Core::Private::Function::TFunctionStorage<0>,void __cdecl(TArray<unsigned char,TSizedDefaultAllocator<32> > const &,FString const &,int const &)>::operator()() [C:\Unreal Engine\UE_5.1\Engine\Source\Runtime\Core\Public\Templates\Function.h:602]
> UnrealEditor_Core!TGraphTask<FAsyncGraphTask>::ExecuteTask() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:1348]
> UnrealEditor_Core!FNamedTaskThread::ProcessTasksNamedThread() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:760]
> UnrealEditor_Core!FNamedTaskThread::ProcessTasksUntilIdle() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:660]
> UnrealEditor_Engine!FFrameEndSync::Sync() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:12391]
> UnrealEditor!FEngineLoop::Tick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5592]
> UnrealEditor!GuardedMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:202]
> UnrealEditor!GuardedMainWrapper() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:107]
> UnrealEditor!LaunchWindowsStartup() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:244]
> UnrealEditor!WinMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:282]
> UnrealEditor!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
> kernel32
> ntdll

**Comment by getnamo** [comment]
Which callback type are you using? Got some examples?

**Comment by Gliptal** [comment]
I tried commenting the `AddDynamic()` call and I still get a crash. I have no other `AddDynamic()` call related to UDPWrapper anywhere in the project.

Does port `55971` ring a bell?

![rider64_xZZ50qBwK9](https://user-images.githubusercontent.com/3907646/226660661-2ebb107f-0877-4680-918a-d129ff607f6e.png)

**Comment by getnamo** [comment]
Looking at https://github.com/getnamo/UDP-Unreal/blob/master/Source/UDPWrapper/Private/UDPComponent.cpp#L270, just checking do you have 'receive data on game thread' enabled? If not it's possible you're getting a callback when the game is being unwound on a separate thread. Test with receive on gamethread enabled and see if that changes anything.

**Comment by wenzheng-wen** [comment]
Hi.So it will work properly on ue5?

**Comment by Gliptal** [comment]
I closed this issue since I haven't seen this error in more than a year.
