### ISSUE TITLE
2.1.0 Version for UE5.1.1 is not working

### ISSUE THREAD

**Issue by Sh4d0wh34rt** [getnamo/UDP-Unreal#38]
If tried downloading and implementing the file into both the Engines Plugin file and my projects file but it continues to come with an error... I have the Socket.io version 2.5.2 would that cause a problem? 
Is it on Marketplace to download?

![image](https://github.com/getnamo/UDP-Unreal/assets/150515700/61d15523-f417-4f22-8d12-48e1b4ab6ad0)

**Comment by getnamo** [comment]
use github releases (.7z downloads, not source), you do not have the required binary files which are included in releases.
