### ISSUE TITLE
Issues building for Avalanche Beta

### ISSUE THREAD

**Issue by bjarque** [getnamo/UDP-Unreal#40]
Hi
Im trying build for 0.1.4 (v5.4.0) Avalanche Beta. I remove the prepending folders for IPAddress.h and changed back "
#include "ThirdParty/libOpus/opus-1.3.1-12/include/opus.h"" in CUOpusCoder.h to get rid of the include errors. But the project still doesnt compile, any pointers to where i should look next?
Any help would be greatly appreciated!

![image](https://github.com/getnamo/UDP-Unreal/assets/23232326/4bf19fa1-b193-4f3e-8812-a45f860afeb3)

**Comment by getnamo** [comment]
Without error codes pointing directly to lines in the plugin, I'm unsure if it's plugin related.

**Comment by bjarque** [comment]
I got it compiled with some help and and by using a clean project. This can be closed.
