### ISSUE TITLE
Upgrade to 5.4

### ISSUE THREAD

**Issue by VitorOI** [getnamo/UDP-Unreal#42]
We're using the Plugin (which is working great!) but we are upgrading to 5.4 and there are some compilation issues 
Thank you!

**Comment by getnamo** [comment]
The plugin will be update in my next OS plugins 5.4 update sweep. If you have any compilation log outputs that may be relevant feel free to post them here. NB if socket.io plugin is the blocker, pull latest master, it should be 5.4 compatible.

**Comment by Gliptal** [comment]
Any news on this?

**Comment by getnamo** [comment]
Release is here: https://github.com/getnamo/UDP-Unreal/releases/tag/v2.4.0
