### ISSUE TITLE
OnReceiveBytes stops broadcasting after 2-3h of runtime

### ISSUE THREAD

**Issue by VitorOI** [getnamo/UDP-Unreal#45]
When our application has been running for about 2-3 hours, we notice it stops receiving and processing data. We concluded that this is related to the OnReceiveBytes delegate, which stops broadcasting altogether. 

We thought it could be related to the delegate FUDPMessageSignature being a dynamic multicast delegate, which is much more performant-heavy than a simple dynamic delegate. Once we changed the delegate to this:

` DECLARE_DYNAMIC_DELEGATE_ThreeParams(FUDPMessageSignature, const TArray<uint8>&, Bytes, const FString&, IPAddress, const int32&, Port);` and let it run for 3 hours, the issue stopped.

Since we do not use the component in blueprints, it seems to have fixed the issue, but we also understand it's not the best solution since it might be needed later on in BP (and that other users of this Component use it in BPs).

Any ideas for a solution that does not involve changing the delegate?

**Comment by VitorOI** [comment]
Update, just tried that fix again but it eventually crashes with a "ProcessDelegate() called with no function name set!"

**Comment by getnamo** [comment]
Probably best to start the debug by tracking what is valid/what isn't valid when you do catch the bug (in e.g. debug mode). It sounds to me like something is being released, invalidating the delegate. Check to see if you're not memory leaking as well.

**Comment by VitorOI** [comment]
We fixed it by checking if the delegate is bound and if not, add it again. I'm not sure why it unbound like that but seems to work correctly now
